### ISSUE TITLE
Final project-Primer Designer

### ISSUE THREAD

**Issue by nadavhen** [szabgab/wis-python-bootcamp-2023-12#45]
https://github.com/nadavhen/PCR-primer-designer/tree/main

**Comment by szabgab** [comment]
Notes:

The content of the requirements.txt file and the instruction in the README file have some differences. Better to keep only the requrements.txt and in the README write `pip install -r requirements.txt`

BTW the README with the images is very nice!

Many functions are way too long. You should consider how to move some part of the code to separate and shorter functions to make them more readable. Try selecting some part of the code and in VSCode use **F2 / Refactor / Extract function**. This might help you extracting functions.

I tried to run it and use the input `AGCT`.

It crashed:


```
$ python Main.py 
['text', 'AGCT']
Traceback (most recent call last):
  File "/home/gabor/work/PCR-primer-designer/Code/Main.py", line 93, in <module>
    main()
  File "/home/gabor/work/PCR-primer-designer/Code/Main.py", line 54, in main
    forward_primer = PrimerDesigner.ListToPrimes(forward_primer)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/work/PCR-primer-designer/Code/PrimerDesigner.py", line 46, in ListToPrimes
    return [Primer(prime) for prime in prime_list]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/work/PCR-primer-designer/Code/PrimerDesigner.py", line 46, in <listcomp>
    return [Primer(prime) for prime in prime_list]
            ^^^^^^^^^^^^^
  File "/home/gabor/work/PCR-primer-designer/Code/PrimerDesigner.py", line 97, in __init__
    self.tm = mt.Tm_NN(sequence)
              ^^^^^^^^^^^^^^^^^^
  File "/home/gabor/venv/lib/python3.11/site-packages/Bio/SeqUtils/MeltingTemp.py", line 1021, in Tm_NN
    ends = seq[0] + seq[-1]
           ~~~^^^
IndexError: string index out of range
```

It should not crash even if the user provides incorrect or insufficient input.
