### ISSUE TITLE
Final project submission - Generating matched patient pairs from an Excel database

### ISSUE THREAD

**Issue by goldahg** [szabgab/wis-python-bootcamp-2023-12#52]
https://github.com/goldahg/Generating-matched-patient-pairs-from-an-Excel-database

Golda, Stav and Doreen

**Comment by szabgab** [comment]
* There is no `.gitignore` file
* all the files except the README are empty

**Comment by goldahg** [comment]
No idea what happened, I re-uploaded them hopefully it should be ok

**Comment by szabgab** [comment]
* There should be a file called `requirements.txt` listing the required modules that apparently also include `openpyxl`
* There are no instruction how to run the tests

```
$ python -m unittest
E
======================================================================
ERROR: test_programs_biobank (unittest.loader._FailedTest.test_programs_biobank)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_programs_biobank
Traceback (most recent call last):
  File "/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/venv/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 419, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 362, in _get_module_from_name
    __import__(name)
  File "/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/test_programs_biobank.py", line 7, in <module>
    df=pd.read_excel('Biobank.xlsx')
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/venv/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/venv/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/venv/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/venv/lib/python3.11/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

after installing `openpyxl` I get this error:

```
$ python -m unittest
number of samples with Gestational diabetes type 1: 158
/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/programs_biobank.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  controlsdf['mothers pathology score'] = df.apply(calculate_row_sum, axis=1)
F/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/programs_biobank.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  controlsdf['mothers pathology score'] = df.apply(calculate_row_sum, axis=1)
.number of samples with Gestational diabetes type 1: 158
.
======================================================================
FAIL: test_file_exists (test_programs_biobank.Test_text_writer.test_file_exists)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/test_programs_biobank.py", line 35, in test_file_exists
    self.assertTrue(os.path.exists(file_name), f"File '{file_name}' does not exist in the current working directory")
AssertionError: False is not true : File 'Matching_controls.txt' does not exist in the current working directory

----------------------------------------------------------------------
Ran 3 tests in 0.328s

FAILED (failures=1)
```

When finally I manage to run the program I get warnings:

```
$ python script_biobank.py 
what is the pathology of interest? 
 1- Preeclampsia 
 2- Gestational diabetes type 1 
 3- Gestational diabetes type 2 
 4- COVID infection 
 Your choice: 1
would you like to use samples that have only one pathology? True/False 
 Your choice: True
number of samples with preeclampsia: 19
/home/gabor/work/Generating-matched-patient-pairs-from-an-Excel-database/programs_biobank.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  controlsdf['mothers pathology score'] = df.apply(calculate_row_sum, axis=1)

 
 Created a file named Matching_controls.txt in the folder, Good luck with the experiment! 
```

* The `Matching_controls.txt` file was generated, but it is not listed in `.gitignore` so one might accidentally add it to git.
