### ISSUE TITLE
qPCR_analyzer

### ISSUE THREAD

**Issue by DafnaBarkan** [szabgab/wis-python-bootcamp-2023-12#53]
https://github.com/DafnaBarkan/qPCR-analyzer/tree/main

**Comment by szabgab** [comment]
* it crashes when I provide input that it does not like:

```
 $ python qPCR_analyzer.py 
Please enter the name of the qPCR result file (including .xls extension): example_input.xls
These are the Worksheets in the file:
['Results', 'test_sheet']
Please enter the name of the relevant worksheet: test_sheet
Traceback (most recent call last):
  File "/home/gabor/work/qPCR-analyzer/qPCR_analyzer.py", line 234, in <module>
    main()
  File "/home/gabor/work/qPCR-analyzer/qPCR_analyzer.py", line 219, in main
    df = preprocess_data(ws)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/work/qPCR-analyzer/qPCR_analyzer.py", line 60, in preprocess_data
    column_names = data[0]
                   ~~~~^^^
IndexError: list index out of range
```

also:

```
 $ python qPCR_analyzer.py 
Please enter the name of the qPCR result file (including .xls extension): example_input.xls
These are the Worksheets in the file:
['Results', 'test_sheet']
Please enter the name of the relevant worksheet: Results
These are the target genes in the file:
['UL44', 'UL55', 'B2M']
Please enter the normalizing target gene: UL55
These are the samples in the file:
['del150a', 'del150b', 'del175a', 'del175b', 'del200a', 'del200b', 'del225a', 'del225b', 'wt30a', 'wt30b', 'wt40a', 'wt40b', 'wt50a', 'wt50b', 'wt60a', 'wt60b', 'wt70a', 'wt70b']
Please enter the reference sample name: del175b
Traceback (most recent call last):
  File "/home/gabor/work/qPCR-analyzer/qPCR_analyzer.py", line 234, in <module>
    main()
  File "/home/gabor/work/qPCR-analyzer/qPCR_analyzer.py", line 226, in main
    analysis_output_save(avg_df, delta_df, delta_delta_df, exp_df,output_dir)
  File "/home/gabor/work/qPCR-analyzer/qPCR_analyzer.py", line 120, in analysis_output_save
    Ct_analysis_df.to_excel(os.path.join(output_dir, 'Ct analysis.xlsx'))
  File "/home/gabor/work/qPCR-analyzer/venv/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/work/qPCR-analyzer/venv/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/work/qPCR-analyzer/venv/lib/python3.11/site-packages/pandas/core/generic.py", line 2374, in to_excel
    formatter.write(
  File "/home/gabor/work/qPCR-analyzer/venv/lib/python3.11/site-packages/pandas/io/formats/excel.py", line 918, in write
    writer = ExcelWriter(  # type: ignore[abstract]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/work/qPCR-analyzer/venv/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 56, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
```


* You don't need to handle missing dependencies in the code and the code should not install dependencies. It should assume the user installed the dependencies. (and it does not even work as the code would not start if either of those dependencies was really missing)
* `pytest` crashes:

```
$ pytest
============================= test session starts ==============================
platform linux -- Python 3.11.6, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/gabor/work/qPCR-analyzer
collected 5 items                                                              

test_qPCR_analyzer.py F...F                                              [100%]

=================================== FAILURES ===================================
__________________________ test_target_fnder_empty_df __________________________

    def test_target_fnder_empty_df():
        test_data = {'Sample Name': [],
                     'Target Name': [],
                     'CT': []
                     }
        test_df = pd.DataFrame(test_data)
        with pytest.raises(SystemExit):
>           target_fnder(test_df)

test_qPCR_analyzer.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
qPCR_analyzer.py:72: in target_fnder
    control_target = input('Please enter the normalizing target gene: ')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_pytest.capture.DontReadFromInput object at 0x7e1d70cb0390>, size = -1

    def read(self, size: int = -1) -> str:
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

venv/lib/python3.11/site-packages/_pytest/capture.py:207: OSError
----------------------------- Captured stdout call -----------------------------
These are the target genes in the file:
[]
Please enter the normalizing target gene: 
_________________________ test_replicate_avg_empty_df __________________________

    def test_replicate_avg_empty_df():
        test_data = {'Sample Name': [],
                     'Target Name': [],
                     'CT': []
                     }
        test_df = pd.DataFrame(test_data)
>       with pytest.raises(SystemExit):
E       Failed: DID NOT RAISE <class 'SystemExit'>

test_qPCR_analyzer.py:57: Failed
=========================== short test summary info ============================
FAILED test_qPCR_analyzer.py::test_target_fnder_empty_df - OSError: pytest: reading from stdin while output is captured!  Consider usi...
FAILED test_qPCR_analyzer.py::test_replicate_avg_empty_df - Failed: DID NOT RAISE <class 'SystemExit'>
========================= 2 failed, 3 passed in 0.44s ==========================
```
